# Generated by Django 4.2.1 on 2023-05-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_category_title_alter_product_title_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name": "image", "verbose_name_plural": "images"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product", "verbose_name_plural": "products"},
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="images/resimyok.jpeg", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="product.category",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                default="images/resimyok.jpeg", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="title",
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="images/resimyok.jpeg", upload_to="images/"
            ),
        ),
    ]
