# Generated by Django 4.2.1 on 2023-05-26 19:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_category_options_alter_images_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="detail",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
