# Generated by Django 4.2.1 on 2023-05-29 13:09

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=django.utils.timezone.now, editable=False, populate_from="title"
            ),
            preserve_default=False,
        ),
    ]
