# Generated by Django 4.2.1 on 2023-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("True", "Evet"), ("False", "Hayır")],
                default="True",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="subject",
            field=models.CharField(max_length=50),
        ),
    ]
