# Generated by Django 4.2.1 on 2023-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_remove_product_price_currency_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
