# Generated by Django 4.2.1 on 2023-05-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("keywords", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("company", models.CharField(blank=True, max_length=50)),
                ("adress", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("fax", models.CharField(blank=True, max_length=15)),
                ("email", models.CharField(blank=True, max_length=50)),
                ("smtpserver", models.CharField(blank=True, max_length=20)),
                ("smtpemail", models.CharField(blank=True, max_length=20)),
                ("smtppassword", models.CharField(blank=True, max_length=10)),
                ("smtpport", models.CharField(blank=True, max_length=5)),
                ("icon", models.ImageField(blank=True, upload_to="images/")),
                ("facebook", models.CharField(blank=True, max_length=50)),
                ("instagram", models.CharField(blank=True, max_length=50)),
                ("twitter", models.CharField(blank=True, max_length=50)),
                ("aboutus", models.TextField(blank=True)),
                ("contact", models.TextField(blank=True)),
                ("references", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("true", "evet"), ("false", "hayır")],
                        max_length=10,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
