# Generated by Django 4.2.1 on 2023-06-08 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(help_text="(5xx-xxx-xx-xx)", max_length=10)),
                ("address", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=150)),
                ("country", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="images/users/defaultprofile.jpeg",
                        upload_to="images/users/",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
