# Generated by Django 4.2.1 on 2023-06-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="images/users/defaultprofile.jpeg", upload_to="images/users/"
            ),
        ),
    ]
