# Generated by Django 4.2.1 on 2023-06-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_remove_order_total_currency_alter_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.FloatField(),
        ),
    ]
